# Generated by Django 2.0.4 on 2018-04-16 22:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('borrowed_at', models.DateTimeField(auto_now_add=True, verbose_name='Borrowed at')),
                ('got_back_at', models.DateTimeField(blank=True, null=True, verbose_name='Got back at')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.Book', verbose_name='Book')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patron', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Patron',
                'verbose_name_plural': 'Patrons',
                'default_related_name': 'patrons',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('review_text', models.TextField(verbose_name='Review text')),
                ('review_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Review score')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.Book', verbose_name='Book')),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patrons.Patron', verbose_name='Patron')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='borrowing',
            name='patron',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patrons.Patron', verbose_name='Patron'),
        ),
    ]
